services:
  oracle:
    image: gvenzl/oracle-free:23-slim
    container_name: denotary-db-agent-oracle-live
    environment:
      ORACLE_PASSWORD: "oraclepw"
      APP_USER: "denotary"
      APP_USER_PASSWORD: "denotarypw"
    ports:
      - "51521:1521"
