services:
  scylladb:
    image: scylladb/scylla:6.0
    container_name: denotary-db-agent-scylladb-live
    command: --overprovisioned 1 --smp 1 --memory 750M --api-address 0.0.0.0
    ports:
      - "59043:9042"
